const routes = require('next-routes')

module.exports = routes()
  .add('/', 'home')
  .add('/signin', 'signin')
  .add('/signup', 'signup')
  .add('/profile/:id', 'profile')
  .add('/wallpaper/create', 'create')
  .add('/wallpaper/:id', 'wallpaper')
  .add('/wallpaper/:id/edit', 'edit')
